### ISSUE TITLE
没有数据

### ISSUE THREAD

**Issue by wcglws** [liuzhao2007/WeexList#1]
楼主还能弄点数据啊

**Comment by liuzhao2007** [comment]
现在有了，更新下，谢谢反馈哈

**Comment by wcglws** [comment]
麻烦了，还有个问题，按照你的demo，自定义下拉刷新的component，在手机上不显示
<img width="1619" alt="wx20180330-111504 2x" src="https://user-images.githubusercontent.com/16982083/38123083-c40c9958-340b-11e8-9fa8-a86649accac2.png">
