### ISSUE TITLE
自定义的组件手机上不显示

### ISSUE THREAD

**Issue by wcglws** [liuzhao2007/WeexList#2]
按照你的demo，自定义下拉刷新的component，在手机上不显示，大神还能指点下，我纯属初学
<img width="1619" alt="pp" src="https://user-images.githubusercontent.com/16982083/38158131-84fda642-34c1-11e8-8f19-9e6dd015dd1c.png">

**Comment by liuzhao2007** [comment]
这个js是原始的，需要编译成bundle才能使用的，你把编译之后的js放到assert里。
